name: adhan_indonesia
description: Indonesian prayer times calculation with altitude support, based on Kemenag (Ministry of Religious Affairs) standards. Extends the adhan package.
version: 1.0.0
homepage: https://github.com/yourusername/adhan_indonesia
publish_to: none # Remove this line when ready to publish to pub.dev

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  adhan:
    path: ../

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0
